window.esdocSearchIndex = [
  [
    "@cedx/gulp-php-minify/lib/fast_transformer.js~fasttransformer",
    "class/lib/fast_transformer.js~FastTransformer.html",
    "<span>FastTransformer</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/fast_transformer.js</span>",
    "class"
  ],
  [
    "@cedx/gulp-php-minify/lib/minifier.js~minifier",
    "class/lib/minifier.js~Minifier.html",
    "<span>Minifier</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/minifier.js</span>",
    "class"
  ],
  [
    "@cedx/gulp-php-minify/lib/safe_transformer.js~safetransformer",
    "class/lib/safe_transformer.js~SafeTransformer.html",
    "<span>SafeTransformer</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/safe_transformer.js</span>",
    "class"
  ],
  [
    "@cedx/gulp-php-minify/lib/minifier.js~transform",
    "variable/index.html#static-variable-Transform",
    "<span>Transform</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/minifier.js</span>",
    "variable"
  ],
  [
    "@cedx/gulp-php-minify/lib/factory.js~factory",
    "function/index.html#static-function-factory",
    "<span>factory</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/factory.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "fasttransformer lib/fast_transformer.js~fasttransformer,fasttransformer",
    "test-file/test/fast_transformer_test.js.html#lineNumber9",
    "FastTransformer",
    "test"
  ],
  [
    "fasttransformer#listening lib/fast_transformer.js~fasttransformer#listening,fasttransformer#listening",
    "test-file/test/fast_transformer_test.js.html#lineNumber15",
    "FastTransformer #listening",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer_test.js.html#lineNumber16",
    "FastTransformer #listening should return whether the server is listening",
    "test"
  ],
  [
    "fasttransformer#transform lib/fast_transformer.js~fasttransformer#transform,fasttransformer#transform",
    "test-file/test/fast_transformer_test.js.html#lineNumber31",
    "FastTransformer #transform()",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer_test.js.html#lineNumber36",
    "FastTransformer #transform() should remove the inline comments",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer_test.js.html#lineNumber44",
    "FastTransformer #transform() should remove the multi-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer_test.js.html#lineNumber50",
    "FastTransformer #transform() should remove the single-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer_test.js.html#lineNumber56",
    "FastTransformer #transform() should remove the whitespace",
    "test"
  ],
  [
    "minifier lib/minifier.js~minifier,minifier",
    "test-file/test/minifier_test.js.html#lineNumber10",
    "Minifier",
    "test"
  ],
  [
    "minifier#_transform minifier#_transform,minifier#_transform",
    "test-file/test/minifier_test.js.html#lineNumber43",
    "Minifier #_transform()",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber50",
    "Minifier #_transform() should remove the inline comments",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber62",
    "Minifier #_transform() should remove the multi-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber72",
    "Minifier #_transform() should remove the single-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber82",
    "Minifier #_transform() should remove the whitespace",
    "test"
  ],
  [
    "minifier#mode lib/minifier.js~minifier#mode,minifier#mode",
    "test-file/test/minifier_test.js.html#lineNumber16",
    "Minifier #mode",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber23",
    "Minifier #mode should be `fast` if the underlying transformer is a `FastTransformer` one",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber17",
    "Minifier #mode should be `safe` if the underlying transformer is a `SafeTransformer` one",
    "test"
  ],
  [
    "",
    "test-file/test/minifier_test.js.html#lineNumber29",
    "Minifier #mode should change the underlying transformer on value update",
    "test"
  ],
  [
    "safetransformer lib/safe_transformer.js~safetransformer,safetransformer",
    "test-file/test/safe_transformer_test.js.html#lineNumber9",
    "SafeTransformer",
    "test"
  ],
  [
    "safetransformer#transform lib/safe_transformer.js~safetransformer#transform,safetransformer#transform",
    "test-file/test/safe_transformer_test.js.html#lineNumber15",
    "SafeTransformer #transform()",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer_test.js.html#lineNumber19",
    "SafeTransformer #transform() should remove the inline comments",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer_test.js.html#lineNumber27",
    "SafeTransformer #transform() should remove the multi-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer_test.js.html#lineNumber33",
    "SafeTransformer #transform() should remove the single-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer_test.js.html#lineNumber39",
    "SafeTransformer #transform() should remove the whitespace",
    "test"
  ],
  [
    "factory lib/factory.js~factory,factory",
    "test-file/test/factory_test.js.html#lineNumber9",
    "factory()",
    "test"
  ],
  [
    "",
    "test-file/test/factory_test.js.html#lineNumber14",
    "factory() should properly initialize the minifier properties",
    "test"
  ],
  [
    "",
    "test-file/test/factory_test.js.html#lineNumber10",
    "factory() should return a `Minifier` instance",
    "test"
  ],
  [
    "lib/factory.js",
    "file/lib/factory.js.html",
    "lib/factory.js",
    "file"
  ],
  [
    "lib/fast_transformer.js",
    "file/lib/fast_transformer.js.html",
    "lib/fast_transformer.js",
    "file"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#close",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-method-close",
    "lib/fast_transformer.js~FastTransformer#close",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#constructor",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-constructor-constructor",
    "lib/fast_transformer.js~FastTransformer#constructor",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#listen",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-method-listen",
    "lib/fast_transformer.js~FastTransformer#listen",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#listening",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-get-listening",
    "lib/fast_transformer.js~FastTransformer#listening",
    "member"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#transform",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-method-transform",
    "lib/fast_transformer.js~FastTransformer#transform",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer.default_address",
    "class/lib/fast_transformer.js~FastTransformer.html#static-get-DEFAULT_ADDRESS",
    "lib/fast_transformer.js~FastTransformer.DEFAULT_ADDRESS",
    "member"
  ],
  [
    "lib/minifier.js",
    "file/lib/minifier.js.html",
    "lib/minifier.js",
    "file"
  ],
  [
    "lib/minifier.js~minifier#binary",
    "class/lib/minifier.js~Minifier.html#instance-member-binary",
    "lib/minifier.js~Minifier#binary",
    "member"
  ],
  [
    "lib/minifier.js~minifier#constructor",
    "class/lib/minifier.js~Minifier.html#instance-constructor-constructor",
    "lib/minifier.js~Minifier#constructor",
    "method"
  ],
  [
    "lib/minifier.js~minifier#mode",
    "class/lib/minifier.js~Minifier.html#instance-get-mode",
    "lib/minifier.js~Minifier#mode",
    "member"
  ],
  [
    "lib/minifier.js~minifier#mode",
    "class/lib/minifier.js~Minifier.html#instance-set-mode",
    "lib/minifier.js~Minifier#mode",
    "member"
  ],
  [
    "lib/minifier.js~minifier#silent",
    "class/lib/minifier.js~Minifier.html#instance-member-silent",
    "lib/minifier.js~Minifier#silent",
    "member"
  ],
  [
    "lib/safe_transformer.js",
    "file/lib/safe_transformer.js.html",
    "lib/safe_transformer.js",
    "file"
  ],
  [
    "lib/safe_transformer.js~safetransformer#constructor",
    "class/lib/safe_transformer.js~SafeTransformer.html#instance-constructor-constructor",
    "lib/safe_transformer.js~SafeTransformer#constructor",
    "method"
  ],
  [
    "lib/safe_transformer.js~safetransformer#transform",
    "class/lib/safe_transformer.js~SafeTransformer.html#instance-method-transform",
    "lib/safe_transformer.js~SafeTransformer#transform",
    "method"
  ],
  [
    "test/factory_test.js",
    "test-file/test/factory_test.js.html",
    "test/factory_test.js",
    "testFile"
  ],
  [
    "test/fast_transformer_test.js",
    "test-file/test/fast_transformer_test.js.html",
    "test/fast_transformer_test.js",
    "testFile"
  ],
  [
    "test/minifier_test.js",
    "test-file/test/minifier_test.js.html",
    "test/minifier_test.js",
    "testFile"
  ],
  [
    "test/safe_transformer_test.js",
    "test-file/test/safe_transformer_test.js.html",
    "test/safe_transformer_test.js",
    "testFile"
  ]
]