window.esdocSearchIndex = [
  [
    "@cedx/gulp-php-minify/lib/fast_transformer.js~fasttransformer",
    "class/lib/fast_transformer.js~FastTransformer.html",
    "<span>FastTransformer</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/fast_transformer.js</span>",
    "class"
  ],
  [
    "@cedx/gulp-php-minify/lib/minifier.js~minifier",
    "class/lib/minifier.js~Minifier.html",
    "<span>Minifier</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/minifier.js</span>",
    "class"
  ],
  [
    "@cedx/gulp-php-minify/lib/safe_transformer.js~safetransformer",
    "class/lib/safe_transformer.js~SafeTransformer.html",
    "<span>SafeTransformer</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/safe_transformer.js</span>",
    "class"
  ],
  [
    "@cedx/gulp-php-minify/lib/minifier.js~transform",
    "variable/index.html#static-variable-Transform",
    "<span>Transform</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/minifier.js</span>",
    "variable"
  ],
  [
    "@cedx/gulp-php-minify/lib/transform_mode.js~transformmode",
    "variable/index.html#static-variable-TransformMode",
    "<span>TransformMode</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/transform_mode.js</span>",
    "variable"
  ],
  [
    "@cedx/gulp-php-minify/lib/minifier.js~transformer",
    "variable/index.html#static-variable-Transformer",
    "<span>Transformer</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/minifier.js</span>",
    "variable"
  ],
  [
    "@cedx/gulp-php-minify/lib/transformer.js~transformer",
    "class/lib/transformer.js~Transformer.html",
    "<span>Transformer</span> <span class=\"search-result-import-path\">@cedx/gulp-php-minify/lib/transformer.js</span>",
    "class"
  ],
  [
    "fasttransformer lib/fast_transformer.js~fasttransformer,fasttransformer",
    "test-file/test/fast_transformer.test.js.html#lineNumber9",
    "FastTransformer",
    "test"
  ],
  [
    "fasttransformer#close lib/fast_transformer.js~fasttransformer#close,fasttransformer#close",
    "test-file/test/fast_transformer.test.js.html#lineNumber16",
    "FastTransformer #close()",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber24",
    "FastTransformer #close() should be callable multiple times",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber19",
    "FastTransformer #close() should complete without any error",
    "test"
  ],
  [
    "fasttransformer#listen lib/fast_transformer.js~fasttransformer#listen,fasttransformer#listen",
    "test-file/test/fast_transformer.test.js.html#lineNumber34",
    "FastTransformer #listen()",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber43",
    "FastTransformer #listen() should be callable multiple times",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber38",
    "FastTransformer #listen() should complete without any error",
    "test"
  ],
  [
    "fasttransformer#listening lib/fast_transformer.js~fasttransformer#listening,fasttransformer#listening",
    "test-file/test/fast_transformer.test.js.html#lineNumber53",
    "FastTransformer #listening",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber56",
    "FastTransformer #listening should return whether the server is listening",
    "test"
  ],
  [
    "fasttransformer#transform lib/fast_transformer.js~fasttransformer#transform,fasttransformer#transform",
    "test-file/test/fast_transformer.test.js.html#lineNumber70",
    "FastTransformer #transform()",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber75",
    "FastTransformer #transform() should remove the inline comments",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber79",
    "FastTransformer #transform() should remove the multi-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber83",
    "FastTransformer #transform() should remove the single-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/fast_transformer.test.js.html#lineNumber87",
    "FastTransformer #transform() should remove the whitespace",
    "test"
  ],
  [
    "minifier lib/minifier.js~minifier,minifier",
    "test-file/test/minifier.test.js.html#lineNumber10",
    "Minifier",
    "test"
  ],
  [
    "minifier#_transform minifier#_transform,minifier#_transform",
    "test-file/test/minifier.test.js.html#lineNumber38",
    "Minifier #_transform()",
    "test"
  ],
  [
    "",
    "test-file/test/minifier.test.js.html#lineNumber42",
    "Minifier #_transform() should remove the comments and whitespace",
    "test"
  ],
  [
    "minifier.factory lib/minifier.js~minifier.factory,minifier.factory",
    "test-file/test/minifier.test.js.html#lineNumber17",
    "Minifier .factory()",
    "test"
  ],
  [
    "",
    "test-file/test/minifier.test.js.html#lineNumber22",
    "Minifier .factory() should properly initialize the instance properties",
    "test"
  ],
  [
    "",
    "test-file/test/minifier.test.js.html#lineNumber18",
    "Minifier .factory() should return a `Minifier` instance",
    "test"
  ],
  [
    "safetransformer lib/safe_transformer.js~safetransformer,safetransformer",
    "test-file/test/safe_transformer.test.js.html#lineNumber9",
    "SafeTransformer",
    "test"
  ],
  [
    "safetransformer#close lib/safe_transformer.js~safetransformer#close,safetransformer#close",
    "test-file/test/safe_transformer.test.js.html#lineNumber16",
    "SafeTransformer #close()",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer.test.js.html#lineNumber24",
    "SafeTransformer #close() should be callable multiple times",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer.test.js.html#lineNumber19",
    "SafeTransformer #close() should complete without any error",
    "test"
  ],
  [
    "safetransformer#transform lib/safe_transformer.js~safetransformer#transform,safetransformer#transform",
    "test-file/test/safe_transformer.test.js.html#lineNumber34",
    "SafeTransformer #transform()",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer.test.js.html#lineNumber39",
    "SafeTransformer #transform() should remove the inline comments",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer.test.js.html#lineNumber43",
    "SafeTransformer #transform() should remove the multi-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer.test.js.html#lineNumber47",
    "SafeTransformer #transform() should remove the single-line comments",
    "test"
  ],
  [
    "",
    "test-file/test/safe_transformer.test.js.html#lineNumber51",
    "SafeTransformer #transform() should remove the whitespace",
    "test"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/fast_transformer.js",
    "file/lib/fast_transformer.js.html",
    "lib/fast_transformer.js",
    "file"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#[symbol.tostringtag]",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-get-[Symbol.toStringTag]",
    "lib/fast_transformer.js~FastTransformer#[Symbol.toStringTag]",
    "member"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#close",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-method-close",
    "lib/fast_transformer.js~FastTransformer#close",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#constructor",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-constructor-constructor",
    "lib/fast_transformer.js~FastTransformer#constructor",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#listen",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-method-listen",
    "lib/fast_transformer.js~FastTransformer#listen",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#listening",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-get-listening",
    "lib/fast_transformer.js~FastTransformer#listening",
    "member"
  ],
  [
    "lib/fast_transformer.js~fasttransformer#transform",
    "class/lib/fast_transformer.js~FastTransformer.html#instance-method-transform",
    "lib/fast_transformer.js~FastTransformer#transform",
    "method"
  ],
  [
    "lib/fast_transformer.js~fasttransformer.defaultaddress",
    "class/lib/fast_transformer.js~FastTransformer.html#static-get-defaultAddress",
    "lib/fast_transformer.js~FastTransformer.defaultAddress",
    "member"
  ],
  [
    "lib/minifier.js",
    "file/lib/minifier.js.html",
    "lib/minifier.js",
    "file"
  ],
  [
    "lib/minifier.js~minifier#[symbol.tostringtag]",
    "class/lib/minifier.js~Minifier.html#instance-get-[Symbol.toStringTag]",
    "lib/minifier.js~Minifier#[Symbol.toStringTag]",
    "member"
  ],
  [
    "lib/minifier.js~minifier#constructor",
    "class/lib/minifier.js~Minifier.html#instance-constructor-constructor",
    "lib/minifier.js~Minifier#constructor",
    "method"
  ],
  [
    "lib/minifier.js~minifier#silent",
    "class/lib/minifier.js~Minifier.html#instance-member-silent",
    "lib/minifier.js~Minifier#silent",
    "member"
  ],
  [
    "lib/minifier.js~minifier.factory",
    "class/lib/minifier.js~Minifier.html#static-method-factory",
    "lib/minifier.js~Minifier.factory",
    "method"
  ],
  [
    "lib/safe_transformer.js",
    "file/lib/safe_transformer.js.html",
    "lib/safe_transformer.js",
    "file"
  ],
  [
    "lib/safe_transformer.js~safetransformer#[symbol.tostringtag]",
    "class/lib/safe_transformer.js~SafeTransformer.html#instance-get-[Symbol.toStringTag]",
    "lib/safe_transformer.js~SafeTransformer#[Symbol.toStringTag]",
    "member"
  ],
  [
    "lib/safe_transformer.js~safetransformer#close",
    "class/lib/safe_transformer.js~SafeTransformer.html#instance-method-close",
    "lib/safe_transformer.js~SafeTransformer#close",
    "method"
  ],
  [
    "lib/safe_transformer.js~safetransformer#constructor",
    "class/lib/safe_transformer.js~SafeTransformer.html#instance-constructor-constructor",
    "lib/safe_transformer.js~SafeTransformer#constructor",
    "method"
  ],
  [
    "lib/safe_transformer.js~safetransformer#transform",
    "class/lib/safe_transformer.js~SafeTransformer.html#instance-method-transform",
    "lib/safe_transformer.js~SafeTransformer#transform",
    "method"
  ],
  [
    "lib/transform_mode.js",
    "file/lib/transform_mode.js.html",
    "lib/transform_mode.js",
    "file"
  ],
  [
    "lib/transformer.js",
    "file/lib/transformer.js.html",
    "lib/transformer.js",
    "file"
  ],
  [
    "lib/transformer.js~transformer#close",
    "class/lib/transformer.js~Transformer.html#instance-method-close",
    "lib/transformer.js~Transformer#close",
    "method"
  ],
  [
    "lib/transformer.js~transformer#constructor",
    "class/lib/transformer.js~Transformer.html#instance-constructor-constructor",
    "lib/transformer.js~Transformer#constructor",
    "method"
  ],
  [
    "lib/transformer.js~transformer#transform",
    "class/lib/transformer.js~Transformer.html#instance-method-transform",
    "lib/transformer.js~Transformer#transform",
    "method"
  ],
  [
    "lib/transformer.js~transformer.factory",
    "class/lib/transformer.js~Transformer.html#static-method-factory",
    "lib/transformer.js~Transformer.factory",
    "method"
  ],
  [
    "test/fast_transformer.test.js",
    "test-file/test/fast_transformer.test.js.html",
    "test/fast_transformer.test.js",
    "testFile"
  ],
  [
    "test/minifier.test.js",
    "test-file/test/minifier.test.js.html",
    "test/minifier.test.js",
    "testFile"
  ],
  [
    "test/safe_transformer.test.js",
    "test-file/test/safe_transformer.test.js.html",
    "test/safe_transformer.test.js",
    "testFile"
  ]
]